--------------------------------------------------------
--  File creato - venerdì-gennaio-20-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOLLETTA
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" 
   (	"NUMERO_FATTURA" VARCHAR2(15 BYTE), 
	"PERIODO" VARCHAR2(24 BYTE), 
	"TOT_PAGARE" NUMBER(9,0), 
	"DATA_EMISSIONE" DATE, 
	"IVA" NUMBER(7,2), 
	"IMPOSTE" NUMBER(6,2), 
	"COSTI_GENERALI" NUMBER(7,2), 
	"SCADENZA" DATE, 
	"CODICE_ATTO" VARCHAR2(8 BYTE) DEFAULT NULL, 
	"CIG" CHAR(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOLLETTA_ACQUA
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ACQUA" 
   (	"COSTO" NUMBER(9,2) DEFAULT NULL, 
	"ACQUEDOTTO" NUMBER(9,2), 
	"FOGNATURA" NUMBER(9,2), 
	"DEPURAZIONE" NUMBER(9,2), 
	"CONSUMO_ACQUA" NUMBER(9,2), 
	"ONERI_PEREQUAZIONE" NUMBER(9,2), 
	"NUMERO_FATTURA" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOLLETTA_ELETTRICA
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ELETTRICA" 
   (	"COSTO" NUMBER(9,2) DEFAULT NULL, 
	"ENERGIA_REATTIVA" NUMBER(9,2), 
	"POTENZA_PRELEVATA" NUMBER(9,2), 
	"CTS" NUMBER(9,2) DEFAULT 0, 
	"ENERGIA_ATTIVA" NUMBER(9,2), 
	"NUMERO_FATTURA" VARCHAR2(15 BYTE), 
	"SERVIZI_RETE" NUMBER(9,2), 
	"SERVIZI_DI_VENDITA" NUMBER(9,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOLLETTA_GAS
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_GAS" 
   (	"TRASPORTO_E_GESTIONE" NUMBER(9,2), 
	"FORNITURA_GAS" NUMBER(9,2), 
	"COSTO" NUMBER(9,2) DEFAULT NULL, 
	"CONSUMO_PDR" NUMBER(9,2), 
	"ONERI_DI_SISTEMA" NUMBER(9,2), 
	"NUMERO_FATTURA" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTRATTO
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" 
   (	"CIG" CHAR(10 BYTE), 
	"POTENZA_CONTRATTUALE" NUMBER(16,4), 
	"CONDIZIONE_MERCATO" VARCHAR2(40 BYTE), 
	"DEPOSITO_CAUZIONALE" NUMBER(9,2) DEFAULT 0, 
	"TIPO_FORNITURA" VARCHAR2(30 BYTE), 
	"STATO" CHAR(1 BYTE), 
	"DATA_CESSAZIONE" DATE DEFAULT NULL, 
	"PROTOCOLLO_CESSAZIONE" VARCHAR2(12 BYTE) DEFAULT NULL, 
	"ADEGUATEZZA" CHAR(2 BYTE), 
	"PROTOCOLLO_ADEGUATEZZA" VARCHAR2(12 BYTE), 
	"DATA_ADEGUATEZZA" DATE, 
	"TIPO" CHAR(1 BYTE), 
	"CENTRO_COSTO" CHAR(10 BYTE), 
	"PARTITA_IVA" VARCHAR2(13 BYTE), 
	"CODICE_POD" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIPENDENTE
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."DIPENDENTE" 
   (	"EMAIL_AZIENDALE" VARCHAR2(50 BYTE), 
	"NOME" VARCHAR2(20 BYTE), 
	"COGNOME" VARCHAR2(20 BYTE), 
	"PRIVILEGIO" CHAR(1 BYTE), 
	"CHIAVE_ACCESSO" CHAR(16 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DISTRETTO
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."DISTRETTO" 
   (	"CODICE_DISTRETTO" CHAR(6 BYTE), 
	"NOME_DISTRETTO" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORNITORE
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."FORNITORE" 
   (	"PARTITA_IVA" VARCHAR2(13 BYTE), 
	"NUMERO_SERVIZIO_CLIENTI" VARCHAR2(10 BYTE), 
	"NUMERO_SEDE" VARCHAR2(11 BYTE), 
	"INDIRIZZO" VARCHAR2(50 BYTE), 
	"PEC" VARCHAR2(50 BYTE), 
	"FAX" VARCHAR2(18 BYTE), 
	"NOME" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANDATO
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."MANDATO" 
   (	"CODICE_ATTO" VARCHAR2(8 BYTE), 
	"DATA_RECAPITO" DATE, 
	"NUMERO_ATTO" VARCHAR2(9 BYTE), 
	"TOTALE_PAGAMENTO" NUMBER(10,2), 
	"EMAIL_AZIENDALE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POD
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."POD" 
   (	"CODICE_POD" VARCHAR2(10 BYTE), 
	"LETTURA_MANUALE" NUMBER(11,3) DEFAULT NULL, 
	"DATA_LETTURA" DATE DEFAULT NULL, 
	"NUMERO_CONTATORE" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STRUTTURA
--------------------------------------------------------

  CREATE TABLE "C##TECNICO_DIPENDENTE"."STRUTTURA" 
   (	"CENTRO_COSTO" CHAR(10 BYTE), 
	"NOME_STRUTTURA" VARCHAR2(50 BYTE), 
	"VIA" VARCHAR2(50 BYTE), 
	"CAP" CHAR(5 BYTE), 
	"SITUAZIONE_GIURIDICA" CHAR(20 BYTE), 
	"CODICE_DISTRETTO" CHAR(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View TABELLONE_STRUTTURA_ACQUA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##TECNICO_DIPENDENTE"."TABELLONE_STRUTTURA_ACQUA" ("CENTRO_COSTO", "DATA_EMISSIONE", "NUMERO_FATTURA", "COSTO", "ACQUEDOTTO", "FOGNATURA", "ONERI_PEREQUAZIONE", "IMPOSTE", "IVA") AS 
  SELECT STRUTTURA.CENTRO_COSTO,
BOLLETTA.DATA_EMISSIONE,BOLLETTA.NUMERO_FATTURA,
BOLLETTA_ACQUA.COSTO,
BOLLETTA_ACQUA.ACQUEDOTTO, BOLLETTA_ACQUA.FOGNATURA,
BOLLETTA_ACQUA.ONERI_PEREQUAZIONE, BOLLETTA.IMPOSTE,
BOLLETTA.IVA
FROM STRUTTURA JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_ACQUA ON BOLLETTA_ACQUA.NUMERO_FATTURA =BOLLETTA.NUMERO_FATTURA
;
--------------------------------------------------------
--  DDL for View TABELLONE_STRUTTURA_GAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##TECNICO_DIPENDENTE"."TABELLONE_STRUTTURA_GAS" ("CENTRO_COSTO", "DATA_EMISSIONE", "NUMERO_FATTURA", "COSTO", "TRASPORTO_E_GESTIONE", "FORNITURA_GAS", "ONERI_DI_SISTEMA", "IMPOSTE", "IVA") AS 
  SELECT STRUTTURA.CENTRO_COSTO,
BOLLETTA.DATA_EMISSIONE,BOLLETTA.NUMERO_FATTURA,
BOLLETTA_GAS.COSTO,
BOLLETTA_GAS.TRASPORTO_E_GESTIONE,
BOLLETTA_GAS.FORNITURA_GAS,
BOLLETTA_GAS.ONERI_DI_SISTEMA, BOLLETTA.IMPOSTE, BOLLETTA.IVA
FROM STRUTTURA JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_GAS ON BOLLETTA_GAS.NUMERO_FATTURA =
BOLLETTA.NUMERO_FATTURA
;
--------------------------------------------------------
--  DDL for View TABELLONE_STRUTTURA_LUCE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##TECNICO_DIPENDENTE"."TABELLONE_STRUTTURA_LUCE" ("CENTRO_COSTO", "DATA_EMISSIONE", "NUMERO_FATTURA", "CODICE_POD", "COSTO", "ENERGIA_ATTIVA", "ENERGIA_REATTIVA", "POTENZA_PRELEVATA", "SERVIZI_DI_VENDITA", "SERVIZI_RETE", "IMPOSTE", "IVA") AS 
  SELECT STRUTTURA.CENTRO_COSTO,
BOLLETTA.DATA_EMISSIONE,BOLLETTA.NUMERO_FATTURA,CONTRATTO.CODICE_POD,
BOLLETTA_ELETTRICA.COSTO, BOLLETTA_ELETTRICA.ENERGIA_ATTIVA,
BOLLETTA_ELETTRICA.ENERGIA_REATTIVA,
BOLLETTA_ELETTRICA.POTENZA_PRELEVATA, SERVIZI_DI_VENDITA,
SERVIZI_RETE, BOLLETTA.IMPOSTE, BOLLETTA.IVA
FROM STRUTTURA JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_ELETTRICA ON BOLLETTA_ELETTRICA.NUMERO_FATTURA =
BOLLETTA.NUMERO_FATTURA
;
REM INSERTING into C##TECNICO_DIPENDENTE.BOLLETTA
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309353','MAY-JUN','2508',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'83644','1110001110');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309357','JAN-FEB','8555',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'11240','9191919161');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2307799','SEP-OCT','1607',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','9191989123');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309999','SEP-OCT','46607',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','9123229193');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309399','SEP-OCT','707',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','0011001110');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309347','SEP-OCT','207',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','919198920 ');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309947','SEP-OCT','4607',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','919198919 ');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309317','SEP-OCT','42601',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','5671989191');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309388','SEP-OCT','42557',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','9191980092');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309344','OCT-NOV','45507',to_date('03-FEB-22','DD-MON-RR'),'400','2302','73432',to_date('03-FEB-22','DD-MON-RR'),'279203','0101010121');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309348','SEP-OCT','22607',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','1010101010');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309349','NOV-DEC','42657',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','0101010101');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309346','NOV-DEC','42657',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','9123989193');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309350','SEP-OCT','22507',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'54647','1100110011');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309351','SEP-OCT','22507',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'54647','9191981194');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309355','FEB-MAR','72507',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'54647','1234567890');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309365','FEB-MAR','72507',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'54647','1234567220');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309352','FEB-MAR','14508',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'54647','0011001100');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309389','FEB-MAR','14508',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'54647','9194569191');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309354','JUN-JUL','272508',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'83644','1110001110');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309322','JUL-AUG','9508',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'278374','1919191919');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309358','MAR-APR','100000',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'11240','1118807710');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309359','APR-MAY','9999',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),'282636','5671989191');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2109361','MAY-JUN','16582',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),null,'9191919161');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2509363','JAN-FEB','8555',to_date('03-FEB-22','DD-MON-RR'),'456,2','300','2302',to_date('03-FEB-22','DD-MON-RR'),null,'5671989191');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('23093333','OCT-NOV','826097',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','9191989191');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2322347','MAR-APR','72607',to_date('03-FEB-22','DD-MON-RR'),'1456,2','460','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','1118801110');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309397','NOV-DEC','72607',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','0101010121');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309227','JUN-JUL','42607',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','9191989191');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA (NUMERO_FATTURA,PERIODO,TOT_PAGARE,DATA_EMISSIONE,IVA,IMPOSTE,COSTI_GENERALI,SCADENZA,CODICE_ATTO,CIG) values ('2309907','JAN-FEB','42607',to_date('03-FEB-22','DD-MON-RR'),'1456,2','400','2302',to_date('03-FEB-22','DD-MON-RR'),'279203','0101010121');
REM INSERTING into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA (COSTO,ACQUEDOTTO,FOGNATURA,DEPURAZIONE,CONSUMO_ACQUA,ONERI_PEREQUAZIONE,NUMERO_FATTURA) values (null,'1300','567','766','8930','44','2309227');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA (COSTO,ACQUEDOTTO,FOGNATURA,DEPURAZIONE,CONSUMO_ACQUA,ONERI_PEREQUAZIONE,NUMERO_FATTURA) values (null,'1300','567','766','8930','44','23093333');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA (COSTO,ACQUEDOTTO,FOGNATURA,DEPURAZIONE,CONSUMO_ACQUA,ONERI_PEREQUAZIONE,NUMERO_FATTURA) values (null,'1300','567','766','8930','44','2309359');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA (COSTO,ACQUEDOTTO,FOGNATURA,DEPURAZIONE,CONSUMO_ACQUA,ONERI_PEREQUAZIONE,NUMERO_FATTURA) values (null,'1300','567','766','8930','44','2309346');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA (COSTO,ACQUEDOTTO,FOGNATURA,DEPURAZIONE,CONSUMO_ACQUA,ONERI_PEREQUAZIONE,NUMERO_FATTURA) values (null,'1300','567','766','8930','44','2309317');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA (COSTO,ACQUEDOTTO,FOGNATURA,DEPURAZIONE,CONSUMO_ACQUA,ONERI_PEREQUAZIONE,NUMERO_FATTURA) values (null,'1300','567','766','8930','44','2509363');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA (COSTO,ACQUEDOTTO,FOGNATURA,DEPURAZIONE,CONSUMO_ACQUA,ONERI_PEREQUAZIONE,NUMERO_FATTURA) values (null,'1300','567','766','8930','44','2309388');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA (COSTO,ACQUEDOTTO,FOGNATURA,DEPURAZIONE,CONSUMO_ACQUA,ONERI_PEREQUAZIONE,NUMERO_FATTURA) values (null,'1300','567','766','8930','44','2309347');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ACQUA (COSTO,ACQUEDOTTO,FOGNATURA,DEPURAZIONE,CONSUMO_ACQUA,ONERI_PEREQUAZIONE,NUMERO_FATTURA) values (null,'1300','567','766','8930','44','2309351');
REM INSERTING into C##TECNICO_DIPENDENTE.BOLLETTA_ELETTRICA
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ELETTRICA (COSTO,ENERGIA_REATTIVA,POTENZA_PRELEVATA,CTS,ENERGIA_ATTIVA,NUMERO_FATTURA,SERVIZI_RETE,SERVIZI_DI_VENDITA) values (null,'300','567','9','24','2309348','900','8273');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ELETTRICA (COSTO,ENERGIA_REATTIVA,POTENZA_PRELEVATA,CTS,ENERGIA_ATTIVA,NUMERO_FATTURA,SERVIZI_RETE,SERVIZI_DI_VENDITA) values (null,'300','567','9','24','2309353','900','8273');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ELETTRICA (COSTO,ENERGIA_REATTIVA,POTENZA_PRELEVATA,CTS,ENERGIA_ATTIVA,NUMERO_FATTURA,SERVIZI_RETE,SERVIZI_DI_VENDITA) values (null,'300','567','9','24','2309354','900','8273');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ELETTRICA (COSTO,ENERGIA_REATTIVA,POTENZA_PRELEVATA,CTS,ENERGIA_ATTIVA,NUMERO_FATTURA,SERVIZI_RETE,SERVIZI_DI_VENDITA) values (null,'300','567','9','24','2309389','900','8273');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ELETTRICA (COSTO,ENERGIA_REATTIVA,POTENZA_PRELEVATA,CTS,ENERGIA_ATTIVA,NUMERO_FATTURA,SERVIZI_RETE,SERVIZI_DI_VENDITA) values (null,'300','567','9','24','2322347','900','8273');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ELETTRICA (COSTO,ENERGIA_REATTIVA,POTENZA_PRELEVATA,CTS,ENERGIA_ATTIVA,NUMERO_FATTURA,SERVIZI_RETE,SERVIZI_DI_VENDITA) values (null,'300','567','9','24','2309355','900','8273');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_ELETTRICA (COSTO,ENERGIA_REATTIVA,POTENZA_PRELEVATA,CTS,ENERGIA_ATTIVA,NUMERO_FATTURA,SERVIZI_RETE,SERVIZI_DI_VENDITA) values (null,'300','567','9','24','2309365','900','8273');
REM INSERTING into C##TECNICO_DIPENDENTE.BOLLETTA_GAS
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309999');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2109361');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309322');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309399');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309397');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309947');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309344');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309349');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309358');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309350');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309352');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2307799');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309357');
Insert into C##TECNICO_DIPENDENTE.BOLLETTA_GAS (TRASPORTO_E_GESTIONE,FORNITURA_GAS,COSTO,CONSUMO_PDR,ONERI_DI_SISTEMA,NUMERO_FATTURA) values ('1300','567',null,'4000','44','2309907');
REM INSERTING into C##TECNICO_DIPENDENTE.CONTRATTO
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('919198919 ','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS2410505','06328131211','132384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('919198920 ','124','FORNITURA ULTIMA ISTANZA','19','BASSA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'A','LDS2410505','06328131211','00068002');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('0101010121','560','FORNITURA ULTIMA ISTANZA','10','Media Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS2410206','06328131211','142384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('1010101010','600','FORNITURA ULTIMA ISTANZA','10','Media Tensione
Trifase','1',null,null,'NO',null,null,'E','LDS2410401','IT06328131211','00186839');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('0101010101','500','FORNITURA ULTIMA ISTANZA','10','Bassa Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS2610505','07679350632','041284');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('1100110011','900','FORNITURA ULTIMA ISTANZA','19','Bassa TensioneTrifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS2610602','07679350632','054284');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('1234567890','1200','FORNITURA ULTIMA ISTANZA','19','ALTA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'E','LDS2810507','06328131211','043458');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('0011001100','120','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','0',to_date('03-FEB-22','DD-MON-RR'),null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS2810206','06328131211','054254');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('1234567220','1200','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'E','LDS2810206','06328131211','054254');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('1110001110','120','FORNITURA ULTIMA ISTANZA','19','ALTA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'E','LDS2910401','07679350632','095384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('1118801110','120','FORNITURA ULTIMA ISTANZA','19','BASSA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'E','LDS2910401','07679350632','043484');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('1118807710','120','FORNITURA ULTIMA ISTANZA','19','BASSA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS2910401','07679350632','052334');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('0011001110','120','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','0',to_date('20-MAR-22','DD-MON-RR'),null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS2810206','06328131211','095384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('1919191919','120','FORNITURA ULTIMA ISTANZA','19','ALTA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS2910505','07679350632','055284');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('9191919191','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','0',to_date('03-FEB-22','DD-MON-RR'),null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDSSA10401','07679350632','012384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('9191919161','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS3010504','06328131211','142394');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('9191980092','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','0',to_date('03-FEB-22','DD-MON-RR'),null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'A','LDS3010406','06328131211','055284');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('9123989193','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'A','LDS2510401','06328131211','112384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('9123229193','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS2510401','06328131211','012384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('9191981194','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','1',null,null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'A','LDS2510602','06328131211','122384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('9191989123','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','0',to_date('03-FEB-22','DD-MON-RR'),null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'G','LDS3110401','06328131211','095384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('9194569191','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','0',to_date('03-FEB-22','DD-MON-RR'),null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'E','LDS3110206','06328131211','082784');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('5671989191','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','0',to_date('03-FEB-22','DD-MON-RR'),null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'A','LDS3010504','06328131211','142384');
Insert into C##TECNICO_DIPENDENTE.CONTRATTO (CIG,POTENZA_CONTRATTUALE,CONDIZIONE_MERCATO,DEPOSITO_CAUZIONALE,TIPO_FORNITURA,STATO,DATA_CESSAZIONE,PROTOCOLLO_CESSAZIONE,ADEGUATEZZA,PROTOCOLLO_ADEGUATEZZA,DATA_ADEGUATEZZA,TIPO,CENTRO_COSTO,PARTITA_IVA,CODICE_POD) values ('9191989191','124','FORNITURA ULTIMA ISTANZA','19','MEDIA Tensione
Trifase','0',to_date('03-FEB-22','DD-MON-RR'),null,'SI',null,to_date('03-FEB-22','DD-MON-RR'),'A','LDS3010504','06328131211','132384');
REM INSERTING into C##TECNICO_DIPENDENTE.DIPENDENTE
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.DIPENDENTE (EMAIL_AZIENDALE,NOME,COGNOME,PRIVILEGIO,CHIAVE_ACCESSO) values ('mauriziospinosa@gmail.com','Maurizio','Spinosa','2','QMWNEBRVTCYZ99P$');
Insert into C##TECNICO_DIPENDENTE.DIPENDENTE (EMAIL_AZIENDALE,NOME,COGNOME,PRIVILEGIO,CHIAVE_ACCESSO) values ('riccardoandreaspinosa@gmail.com','Riccardo
Andrea','Spinosa','1','QOWNEBHVTCYZ89P$');
Insert into C##TECNICO_DIPENDENTE.DIPENDENTE (EMAIL_AZIENDALE,NOME,COGNOME,PRIVILEGIO,CHIAVE_ACCESSO) values ('alessandromassadoro@live.it','Alessandro','Massadoro','1','ALWNEBHVTCYZ89P$');
Insert into C##TECNICO_DIPENDENTE.DIPENDENTE (EMAIL_AZIENDALE,NOME,COGNOME,PRIVILEGIO,CHIAVE_ACCESSO) values ('palloncinodolce@live.it','Alessandro','Dolce','0','DOWNEBHVTCYZ89P$');
REM INSERTING into C##TECNICO_DIPENDENTE.DISTRETTO
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.DISTRETTO (CODICE_DISTRETTO,NOME_DISTRETTO) values ('SJK4BZ','Distretto Sanitario 24');
Insert into C##TECNICO_DIPENDENTE.DISTRETTO (CODICE_DISTRETTO,NOME_DISTRETTO) values ('K28ACH','Distretto Sanitario 25');
Insert into C##TECNICO_DIPENDENTE.DISTRETTO (CODICE_DISTRETTO,NOME_DISTRETTO) values ('6C33FX','DISTRETTO SANITARIO 26');
Insert into C##TECNICO_DIPENDENTE.DISTRETTO (CODICE_DISTRETTO,NOME_DISTRETTO) values ('0RZBGZ','DISTRETTO SANITARIO 28');
Insert into C##TECNICO_DIPENDENTE.DISTRETTO (CODICE_DISTRETTO,NOME_DISTRETTO) values ('PYCBDK','DISTRETTO SANITARIO 29');
Insert into C##TECNICO_DIPENDENTE.DISTRETTO (CODICE_DISTRETTO,NOME_DISTRETTO) values ('0RZBGS','DISTRETTO SANITARIO 30');
Insert into C##TECNICO_DIPENDENTE.DISTRETTO (CODICE_DISTRETTO,NOME_DISTRETTO) values ('7P4NCT','DISTRETTO SANITARIO 31');
REM INSERTING into C##TECNICO_DIPENDENTE.FORNITORE
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.FORNITORE (PARTITA_IVA,NUMERO_SERVIZIO_CLIENTI,NUMERO_SEDE,INDIRIZZO,PEC,FAX,NOME) values ('IT06328131211','0542843189',null,'Via Molino Rosso, 8 - 40026 Imola
(BO)','clienti.MUI@gruppohera.it',null,'HERA COMM S.p.A.');
Insert into C##TECNICO_DIPENDENTE.FORNITORE (PARTITA_IVA,NUMERO_SERVIZIO_CLIENTI,NUMERO_SEDE,INDIRIZZO,PEC,FAX,NOME) values ('06328131211',null,'800104104','Corso Umberto I, 330/D,
Marigliano','clienti@estraspa.it',null,'Estra');
Insert into C##TECNICO_DIPENDENTE.FORNITORE (PARTITA_IVA,NUMERO_SERVIZIO_CLIENTI,NUMERO_SEDE,INDIRIZZO,PEC,FAX,NOME) values ('07679350632','800884021','800009585','Via Ventaglieri 83, 80135
Napoli','segreteriagenerale@abcnapoli.telecompost.it',null,'Acqua Bene Comune Napoli');
REM INSERTING into C##TECNICO_DIPENDENTE.MANDATO
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.MANDATO (CODICE_ATTO,DATA_RECAPITO,NUMERO_ATTO,TOTALE_PAGAMENTO,EMAIL_AZIENDALE) values ('54647',to_date('28-FEB-22','DD-MON-RR'),'04','1300000','mauriziospinosa@gmail.com');
Insert into C##TECNICO_DIPENDENTE.MANDATO (CODICE_ATTO,DATA_RECAPITO,NUMERO_ATTO,TOTALE_PAGAMENTO,EMAIL_AZIENDALE) values ('279203',to_date('28-FEB-22','DD-MON-RR'),'03','1800000','mauriziospinosa@gmail.com');
Insert into C##TECNICO_DIPENDENTE.MANDATO (CODICE_ATTO,DATA_RECAPITO,NUMERO_ATTO,TOTALE_PAGAMENTO,EMAIL_AZIENDALE) values ('83644',to_date('28-FEB-22','DD-MON-RR'),'09','1100000','mauriziospinosa@gmail.com');
Insert into C##TECNICO_DIPENDENTE.MANDATO (CODICE_ATTO,DATA_RECAPITO,NUMERO_ATTO,TOTALE_PAGAMENTO,EMAIL_AZIENDALE) values ('278374',to_date('03-FEB-22','DD-MON-RR'),'02','10000','alessandromassadoro@live.it');
Insert into C##TECNICO_DIPENDENTE.MANDATO (CODICE_ATTO,DATA_RECAPITO,NUMERO_ATTO,TOTALE_PAGAMENTO,EMAIL_AZIENDALE) values ('11240',to_date('03-FEB-22','DD-MON-RR'),'09','1230000','riccardoandreaspinosa@gmail.com');
Insert into C##TECNICO_DIPENDENTE.MANDATO (CODICE_ATTO,DATA_RECAPITO,NUMERO_ATTO,TOTALE_PAGAMENTO,EMAIL_AZIENDALE) values ('282636',to_date('03-FEB-22','DD-MON-RR'),'05','1280000','palloncinodolce@live.it');
REM INSERTING into C##TECNICO_DIPENDENTE.POD
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('00186839','222300,36',to_date('10-NOV-20','DD-MON-RR'),null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('041284',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('054284',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('043458',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('095384',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('082784',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('055284',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('043484',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('054254',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('041454',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('052334',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('012384',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('112384',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('122384',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('132384',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('142384',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('142394',null,null,null);
Insert into C##TECNICO_DIPENDENTE.POD (CODICE_POD,LETTURA_MANUALE,DATA_LETTURA,NUMERO_CONTATORE) values ('00068002','1540',to_date('03-FEB-22','DD-MON-RR'),null);
REM INSERTING into C##TECNICO_DIPENDENTE.STRUTTURA
SET DEFINE OFF;
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2410505','RSA','Via
Vincenzo padula 1','80123','PROPRIETA           ','SJK4BZ');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2410206','Loreto
Crispi','Via Michelangelo Schipa 9','80122','PROPRIETA           ','SJK4BZ');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2410401','SEDE','Via
Chiatamone 33','81040','PROPRIETA           ','SJK4BZ');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2610505','Fasce deboli
RSA','Via Adriano 117','81055','PROPRIETA           ','6C33FX');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2610602','Materno
infantile','Via Giorgio De Grassi ','80126','PROPRIETA           ','6C33FX');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2810507','RSA','Via
Emilio Scaglione 498','80129','FITTO               ','0RZBGZ');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2810206','SCIUTI','Via
San Gennaro ad Antignano 42','80145','PROPRIETA           ','0RZBGZ');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2910401','SAN
GENNARO','VIA S GENNARO POV 23A','80136','PROPRIETA           ','PYCBDK');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2910206','Poliambulatorio','CORSO AMEDEO SAVOIA 220','80136','PROPRIETA           ','PYCBDK');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2910505','RSA','Via
Fratelli Cervi ','80131','FITTO               ','PYCBDK');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDSSA10401','ELENA D
AOSTA','VIA CAGNAZZI L EM 29','80136','PROPRIETA           ','PYCBDK');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS3010504','ASSISTENZA
ANZIANI','Corso Secondigliano 209','80144','FITTO               ','0RZBGS');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS3010406','MEDICINA
LEGALE','Via Janfolla 444','80145','FITTO               ','0RZBGZ');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2510401','Sede
Distretto','Via degni','80125','FITTO               ','K28ACH');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS2510602','FUTURO
MATERNO INFANTILE E GINECOLOGIA','Via Winspeare 6','80125','PROPRIETA           ','K28ACH');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS3110401','Sede
Distretto','Via Vespucci 9','80142','FITTO               ','7P4NCT');
Insert into C##TECNICO_DIPENDENTE.STRUTTURA (CENTRO_COSTO,NOME_STRUTTURA,VIA,CAP,SITUAZIONE_GIURIDICA,CODICE_DISTRETTO) values ('LDS3110206','SS.
ANNUNZIATA','VIA EGIZIACA A FORCELLA n° 18','80139','PROPRIETA           ','7P4NCT');
--------------------------------------------------------
--  DDL for Procedure CAMBIO_PERMESSI
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##TECNICO_DIPENDENTE"."CAMBIO_PERMESSI" (EMAIL CHAR, PER CHAR)
IS
ERRORE EXCEPTION;
CON_EMAIL CHAR(50);
BEGIN
SELECT EMAIL_AZIENDALE INTO CON_EMAIL FROM DIPENDENTE WHERE
EMAIL_AZIENDALE = EMAIL;
IF (PER < '0') OR (PER >'3') THEN
RAISE ERRORE;
END IF;
UPDATE DIPENDENTE
SET PRIVILEGIO = PER
WHERE EMAIL_AZIENDALE = EMAIL;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20100,'EMAIL NON ESISTENTE');
WHEN ERRORE THEN
RAISE_APPLICATION_ERROR(-20120,'PERMESSO NON VALIDO');
END;

/
--------------------------------------------------------
--  DDL for Procedure CREAZIONE_CHIAVI
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##TECNICO_DIPENDENTE"."CREAZIONE_CHIAVI" (EMAIL CHAR)
IS
PASS CHAR(16);
NOME_PR VARCHAR(20);
BEGIN
SELECT NOME INTO NOME_PR FROM DIPENDENTE WHERE EMAIL_AZIENDALE =
EMAIL; SELECT FUNZIONE_DI_HASHING(3,3,6,4) INTO PASS FROM DUAL;
UPDATE DIPENDENTE
SET CHIAVE_ACCESSO = PASS WHERE EMAIL_AZIENDALE = EMAIL;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20100,'ERRORE');
END;

/
--------------------------------------------------------
--  DDL for Procedure PAGAMENTO_BOLLETTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##TECNICO_DIPENDENTE"."PAGAMENTO_BOLLETTA" (N_FATT char, COD_ATT
char)
IS
TOPOLINO VARCHAR(15);
PLUTO VARCHAR(8);
SCOOBYDOO VARCHAR(8);
ERRORE EXCEPTION;
PAPERINO EXCEPTION;
OK NUMBER(2,0);
BEGIN
--eccezione codice atto non esistente
SELECT(CODICE_ATTO) INTO PLUTO
FROM MANDATO
WHERE MANDATO.CODICE_ATTO=COD_ATT;
--eccezion numero fattura non esistente
SELECT (BOLLETTA.NUMERO_FATTURA) INTO SCOOBYDOO
FROM BOLLETTA
WHERE BOLLETTA.NUMERO_FATTURA=N_FATT;
SELECT COUNT(*) INTO OK
FROM BOLLETTA
JOIN MANDATO ON BOLLETTA.CODICE_ATTO = MANDATO.CODICE_ATTO
WHERE BOLLETTA.NUMERO_FATTURA=N_FATT AND BOLLETTA.CODICE_ATTO IS
NOT NULL;
IF OK = 1 THEN
RAISE ERRORE;
END IF;
UPDATE BOLLETTA
SET CODICE_ATTO = COD_ATT
WHERE NUMERO_FATTURA = N_FATT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20090,'PAGAMENTO ANNULLATO');
WHEN ERRORE THEN
RAISE_APPLICATION_ERROR(-20090,'PAGAMENTO ANNULLATO');
END PAGAMENTO_BOLLETTA;

/
--------------------------------------------------------
--  DDL for Procedure SPESE_TOT_BOLLETTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##TECNICO_DIPENDENTE"."SPESE_TOT_BOLLETTE" (DATAIN CHAR,
DISTRETTO1 CHAR)
IS
TOTALE NUMBER;
anno_futuro EXCEPTION;
PIPPO CHAR (1);
DISTRETTO_INESISTENTE CHAR(6);
app bolletta.TOT_PAGARE%type;
app1 CONTRATTO.TIPO%type;
CURSOR c1
IS (
SELECT SUM(TOT_PAGARE) as Totale, CONTRATTO.TIPO as Tipo
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= '2021' AND
DISTRETTO.CODICE_DISTRETTO ='SJK4BZ'
GROUP BY CONTRATTO.TIPO);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
IF DATAIN>TO_CHAR(sysdate,'yyyy')THEN
RAISE anno_futuro;
END IF;
OPEN c1;
FETCH c1 INTO app,app1;
WHILE c1%FOUND LOOP
DBMS_OUTPUT.PUT_LINE('Tipo = ' || app1 ||' Totale =' || app);
FETCH c1 INTO app,app1;
END LOOP;
EXCEPTION
when anno_futuro then
RAISE_APPLICATION_ERROR(-20010,'ANNO INESISTENTE');
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20011,'DISTRETTO INESISTENTE');
END SPESE_TOT_BOLLETTE;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_ADEGUATEZZA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##TECNICO_DIPENDENTE"."UPDATE_ADEGUATEZZA" (CON_CIG CHAR,
DATA_ADE DATE, PROT CHAR)
IS
CIG_CONT CHAR(10);
CIG_EXCEPT EXCEPTION;
DATA_FUTURA EXCEPTION;
BEGIN
SELECT CIG INTO CIG_CONT
FROM CONTRATTO WHERE CIG= CON_CIG;
IF DATA_ADE > SYSDATE THEN
RAISE DATA_FUTURA;
END IF;
UPDATE CONTRATTO SET ADEGUATEZZA = 'SI', DATA_ADEGUATEZZA= DATA_ADE,
PROTOCOLLO_ADEGUATEZZA = PROT
WHERE CIG = CON_CIG;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20015,'CONTRATTO INESISTENTE');
WHEN DATA_FUTURA THEN
RAISE_APPLICATION_ERROR(-20010,'DATA_ERRATA');
END UPDATE_ADEGUATEZZA;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_CONTRATTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##TECNICO_DIPENDENTE"."UPDATE_CONTRATTO" (CON_CIG CHAR,
DATA_CES DATE, PROT CHAR)
IS
CIG_CONT CHAR(10);
DATA_FUTURA EXCEPTION;
ERRORE EXCEPTION;
ATTIVO CHAR(1);
BEGIN
SELECT CIG INTO CIG_CONT
FROM CONTRATTO WHERE CIG= CON_CIG;
IF DATA_CES > SYSDATE THEN
RAISE DATA_FUTURA;
END IF;
SELECT STATO INTO ATTIVO
FROM CONTRATTO
WHERE CIG = CON_CIG;
IF ATTIVO = '0' THEN
RAISE ERRORE;
END IF;
UPDATE CONTRATTO SET DATA_CESSAZIONE = DATA_CES, STATO= '0',
PROTOCOLLO_CESSAZIONE = PROT
WHERE CIG = CON_CIG;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20015,'CONTRATTO ERRATO');
WHEN DATA_FUTURA THEN
RAISE_APPLICATION_ERROR(-20010,'DATA ERRATA');
WHEN ERRORE THEN
RAISE_APPLICATION_ERROR(-20030,'CONTRATTO GIÀ INATTIVO');
END UPDATE_CONTRATTO;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_LETTURA_POD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##TECNICO_DIPENDENTE"."UPDATE_LETTURA_POD" (DATA_LET DATE, POD1
CHAR, LETTURA NUMBER, BOLLETTA1 CHAR)
IS
CONTROLLO CHAR(1);
CON_NUM NUMBER(10,2);
ECC EXCEPTION;
BEGIN
UPDATE POD
SET DATA_LETTURA = DATA_LET, LETTURA_MANUALE = LETTURA
WHERE CODICE_POD = POD1;
SELECT TIPO INTO CONTROLLO
FROM POD JOIN CONTRATTO ON CONTRATTO.CODICE_POD = POD.CODICE_POD
WHERE POD.CODICE_POD = POD1 AND CONTRATTO.STATO = '1';
IF CONTROLLO = 'A' THEN
SELECT COSTO INTO CON_NUM
FROM POD JOIN CONTRATTO ON CONTRATTO.CODICE_POD = POD.CODICE_POD
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_ACQUA ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_ACQUA.NUMERO_FATTURA
WHERE BOLLETTA.NUMERO_FATTURA = BOLLETTA1;
IF CON_NUM != LETTURA THEN
RAISE ECC;
END IF;
END IF;
IF CONTROLLO = 'G' THEN
SELECT COSTO INTO CON_NUM
FROM POD JOIN CONTRATTO ON CONTRATTO.CODICE_POD =
POD.CODICE_POD
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_GAS ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_GAS.NUMERO_FATTURA
WHERE BOLLETTA.NUMERO_FATTURA = BOLLETTA1;
IF CON_NUM != LETTURA THEN
RAISE ECC;
END IF;
END IF;
IF CONTROLLO = 'E' THEN
SELECT COSTO INTO CON_NUM
FROM POD JOIN CONTRATTO ON CONTRATTO.CODICE_POD =
POD.CODICE_POD
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_ELETTRICA ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_ELETTRICA.NUMERO_FATTURA
WHERE BOLLETTA.NUMERO_FATTURA = BOLLETTA1;
IF CON_NUM != LETTURA THEN
RAISE ECC;
END IF;
END IF;
EXCEPTION
WHEN ECC THEN
DBMS_OUTPUT.PUT_LINE('La lettura inserita non corrisponde con quella della bolletta,
attenzione!');
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20022, 'ERRORE');
END;

/
--------------------------------------------------------
--  DDL for Function CALCOLO_CONSUMO_ANNUO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "C##TECNICO_DIPENDENTE"."CALCOLO_CONSUMO_ANNUO" (ANNO CHAR,
DISTRETTO1 CHAR)
RETURN NUMBER IS
CONSUMO_E NUMBER(8,2);
CONSUMO_A NUMBER(8,2);
CONSUMO_G NUMBER(8,2);
CONSUMO_TOT NUMBER (12,2);
ANNO_FUTURO EXCEPTION;
DISTRETTO_INESISTENTE CHAR(6);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
IF ANNO>TO_CHAR(SYSDATE,'YYYY') THEN
RAISE ANNO_FUTURO;
END IF;
SELECT SUM(COSTO) INTO CONSUMO_E
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
JOIN BOLLETTA_ELETTRICA ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_ELETTRICA.NUMERO_FATTURA
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
SELECT SUM(COSTO) INTO CONSUMO_A
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
JOIN BOLLETTA_ACQUA ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_ACQUA.NUMERO_FATTURA
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
SELECT SUM(COSTO) INTO CONSUMO_G
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
JOIN BOLLETTA_GAS ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_GAS.NUMERO_FATTURA
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
CONSUMO_TOT := CONSUMO_G +CONSUMO_A+CONSUMO_E;
RETURN CONSUMO_TOT;
EXCEPTION
WHEN ANNO_FUTURO THEN
RAISE_APPLICATION_ERROR(-20010,'ANNO ERRATO');
RETURN NULL;
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR (-20011,'DISTRETTO INESISTENTE');
RETURN NULL;
END CALCOLO_CONSUMO_ANNUO;

/
--------------------------------------------------------
--  DDL for Function CALCOLO_IVA_ANNUO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "C##TECNICO_DIPENDENTE"."CALCOLO_IVA_ANNUO" (ANNO CHAR, DISTRETTO1
CHAR)
RETURN NUMBER IS
IVA_TOT NUMBER(8,2);
ANNO_FUTURO EXCEPTION;
DISTRETTO_INESISTENTE CHAR(6);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
IF ANNO>TO_CHAR(SYSDATE,'YYYY') THEN
RAISE ANNO_FUTURO;
END IF;
SELECT SUM(IVA) INTO IVA_TOT
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
RETURN IVA_TOT;
EXCEPTION
WHEN ANNO_FUTURO THEN
RAISE_APPLICATION_ERROR(-20010,'Anno errato');
RETURN NULL;
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20011,'DISTRETTO ERRATO');
RETURN NULL;
END CALCOLO_IVA_ANNUO;

/
--------------------------------------------------------
--  DDL for Function CALCOLO_POTENZA_ANNUO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "C##TECNICO_DIPENDENTE"."CALCOLO_POTENZA_ANNUO" (ANNO CHAR,
DISTRETTO1 CHAR)
RETURN NUMBER IS
POTENZA_TOT NUMBER(8,2);
ANNO_FUTURO EXCEPTION;
DISTRETTO_INESISTENTE CHAR(6);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
IF ANNO>TO_CHAR(SYSDATE,'YYYY') THEN
RAISE ANNO_FUTURO;
END IF;
SELECT SUM(POTENZA_PRELEVATA) INTO POTENZA_TOT
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG JOIN BOLLETTA_ELETTRICA
ON BOLLETTA.NUMERO_FATTURA = BOLLETTA_ELETTRICA.NUMERO_FATTURA
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
RETURN POTENZA_TOT;
EXCEPTION
WHEN ANNO_FUTURO THEN
RAISE_APPLICATION_ERROR(-20010,'ANNO ERRATO');
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20011,'DISTRETTO NON ESISTENTE');
RETURN NULL;
END CALCOLO_POTENZA_ANNUO;

/
--------------------------------------------------------
--  DDL for Function CALCOLO_POTENZA_MEDIA_ANNUO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "C##TECNICO_DIPENDENTE"."CALCOLO_POTENZA_MEDIA_ANNUO" (ANNO
CHAR, DISTRETTO1 CHAR)
RETURN NUMBER IS
POT_PREL NUMBER(9,2);
ANNO_FUTURO EXCEPTION;
DISTRETTO_INESISTENTE CHAR(6);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
IF ANNO>TO_CHAR(SYSDATE,'YYYY') THEN
RAISE ANNO_FUTURO;
END IF;
SELECT AVG(POTENZA_PRELEVATA) INTO POT_PREL FROM BOLLETTA_ELETTRICA
JOIN BOLLETTA ON
BOLLETTA.NUMERO_FATTURA=BOLLETTA_ELETTRICA.NUMERO_FATTURA
JOIN CONTRATTO ON CONTRATTO.CIG = BOLLETTA.CIG JOIN STRUTTURA ON
STRUTTURA.CENTRO_COSTO=CONTRATTO.CENTRO_COSTO
JOIN DISTRETTO ON
DISTRETTO.CODICE_DISTRETTO=STRUTTURA.CODICE_DISTRETTO WHERE
EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE) = ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
RETURN POT_PREL;
EXCEPTION
WHEN ANNO_FUTURO THEN
RAISE_APPLICATION_ERROR(-20010,'Anno errato');
RETURN NULL;
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20011,'DISTRETTO ERRATO');
RETURN NULL;
END CALCOLO_POTENZA_MEDIA_ANNUO;

/
--------------------------------------------------------
--  DDL for Function CALCOLO_TOT_PAGARE_ANNUO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "C##TECNICO_DIPENDENTE"."CALCOLO_TOT_PAGARE_ANNUO" (ANNO CHAR,
DISTRETTO CHAR)
RETURN NUMBER IS
PAGARE_TOT NUMBER(8,2);
ANNO_FUTURO EXCEPTION;
DISTRETTO_INESISTENTE CHAR(6);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO;
IF ANNO>TO_CHAR(SYSDATE,'YYYY') THEN
RAISE ANNO_FUTURO;
END IF;
SELECT SUM(TOT_PAGARE) INTO PAGARE_TOT
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO;
RETURN PAGARE_TOT;
EXCEPTION
WHEN ANNO_FUTURO THEN
RAISE_APPLICATION_ERROR(-20010,'Anno errato');
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20011,'DISTRETTO NON ESISTENTE');
RETURN NULL;
END CALCOLO_TOT_PAGARE_ANNUO;

/
--------------------------------------------------------
--  DDL for Function FUNZIONE_DI_HASHING
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "C##TECNICO_DIPENDENTE"."FUNZIONE_DI_HASHING" (
nums IN NUMBER,
ch_sp IN NUMBER,
ch_min IN NUMBER,
ch_maiusc IN NUMBER) return varchar2
IS
lun number := nums + ch_sp + ch_min + ch_maiusc;
pw varchar2(200);
v_iterations number := 0;
max_iter number := 500;
BEGIN
loop
pw := dbms_random.string('p',lun);
v_iterations := v_iterations + 1;
exit when (regexp_count(pw,'[a-z]') = ch_min
and regexp_count(pw,'[A-Z]') = ch_maiusc
and regexp_count(pw,'[0-9]') = nums)
or v_iterations=max_iter;
end loop;
if v_iterations = max_iter THEN
pw := '';
end if;
return(pw);
END;

/
--------------------------------------------------------
--  DDL for Function TOT_PAGARE_PRECEDENTE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "C##TECNICO_DIPENDENTE"."TOT_PAGARE_PRECEDENTE" (N_FATT VARCHAR)
RETURN NUMBER IS
SCOOBYDOO VARCHAR(15);
MINNIE NUMBER (9,2);
RONNIE DATE;
D_BOLLETTA DATE;
BEGIN
SELECT (BOLLETTA.NUMERO_FATTURA) INTO SCOOBYDOO FROM BOLLETTA
WHERE BOLLETTA.NUMERO_FATTURA=N_FATT;
SELECT (DATA_EMISSIONE) INTO D_BOLLETTA FROM BOLLETTA WHERE
BOLLETTA.NUMERO_FATTURA=N_FATT;
SELECT TOT_PAGARE INTO MINNIE FROM BOLLETTA WHERE DATA_EMISSIONE =
(SELECT MAX(DATA_EMISSIONE) FROM BOLLETTA WHERE DATA_EMISSIONE
<D_BOLLETTA);
RETURN MINNIE;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20012,'FATTURA ERRATA');
RETURN NULL;
END TOT_PAGARE_PRECEDENTE;

/
--------------------------------------------------------
--  Constraints for Table DIPENDENTE
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."DIPENDENTE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."DIPENDENTE" MODIFY ("COGNOME" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."DIPENDENTE" MODIFY ("PRIVILEGIO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."DIPENDENTE" ADD CONSTRAINT "CHECK_PRIVILEGIO" CHECK (PRIVILEGIO IN ('0','1','2')) ENABLE;
  ALTER TABLE "C##TECNICO_DIPENDENTE"."DIPENDENTE" ADD PRIMARY KEY ("EMAIL_AZIENDALE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOLLETTA_GAS
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_GAS" MODIFY ("TRASPORTO_E_GESTIONE" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_GAS" MODIFY ("FORNITURA_GAS" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_GAS" MODIFY ("CONSUMO_PDR" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_GAS" MODIFY ("ONERI_DI_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_GAS" ADD PRIMARY KEY ("NUMERO_FATTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOLLETTA_ELETTRICA
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ELETTRICA" MODIFY ("ENERGIA_REATTIVA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ELETTRICA" MODIFY ("POTENZA_PRELEVATA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ELETTRICA" MODIFY ("ENERGIA_ATTIVA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ELETTRICA" MODIFY ("NUMERO_FATTURA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ELETTRICA" ADD PRIMARY KEY ("NUMERO_FATTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOLLETTA
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" MODIFY ("TOT_PAGARE" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" MODIFY ("DATA_EMISSIONE" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" MODIFY ("IVA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" MODIFY ("IMPOSTE" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" MODIFY ("COSTI_GENERALI" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" MODIFY ("SCADENZA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" MODIFY ("CIG" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" ADD PRIMARY KEY ("NUMERO_FATTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTRATTO
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" MODIFY ("POTENZA_CONTRATTUALE" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" MODIFY ("CONDIZIONE_MERCATO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" MODIFY ("TIPO_FORNITURA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" MODIFY ("STATO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" MODIFY ("ADEGUATEZZA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" MODIFY ("CENTRO_COSTO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" MODIFY ("PARTITA_IVA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" MODIFY ("CODICE_POD" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" ADD CONSTRAINT "CHECK_STATO" CHECK (STATO IN ('0','1')) ENABLE;
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" ADD CONSTRAINT "CHECK_ENERGIA" CHECK (TIPO IN ('G','E','A')) ENABLE;
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" ADD CONSTRAINT "CHECK_ADEGUATEZZA" CHECK (ADEGUATEZZA IN ('SI','NO')) ENABLE;
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" ADD PRIMARY KEY ("CIG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POD
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."POD" ADD PRIMARY KEY ("CODICE_POD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORNITORE
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."FORNITORE" MODIFY ("INDIRIZZO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."FORNITORE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."FORNITORE" ADD PRIMARY KEY ("PARTITA_IVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANDATO
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."MANDATO" MODIFY ("DATA_RECAPITO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."MANDATO" MODIFY ("EMAIL_AZIENDALE" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."MANDATO" ADD PRIMARY KEY ("CODICE_ATTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOLLETTA_ACQUA
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ACQUA" MODIFY ("ACQUEDOTTO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ACQUA" MODIFY ("FOGNATURA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ACQUA" MODIFY ("DEPURAZIONE" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ACQUA" MODIFY ("CONSUMO_ACQUA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ACQUA" MODIFY ("ONERI_PEREQUAZIONE" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ACQUA" MODIFY ("NUMERO_FATTURA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ACQUA" ADD PRIMARY KEY ("NUMERO_FATTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISTRETTO
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."DISTRETTO" MODIFY ("NOME_DISTRETTO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."DISTRETTO" ADD PRIMARY KEY ("CODICE_DISTRETTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STRUTTURA
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."STRUTTURA" MODIFY ("NOME_STRUTTURA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."STRUTTURA" MODIFY ("VIA" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."STRUTTURA" MODIFY ("CODICE_DISTRETTO" NOT NULL ENABLE);
  ALTER TABLE "C##TECNICO_DIPENDENTE"."STRUTTURA" ADD PRIMARY KEY ("CENTRO_COSTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOLLETTA
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" ADD CONSTRAINT "FK_MANDATO1" FOREIGN KEY ("CODICE_ATTO")
	  REFERENCES "C##TECNICO_DIPENDENTE"."MANDATO" ("CODICE_ATTO") ENABLE;
  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA" ADD CONSTRAINT "FK_CONTRATTO1" FOREIGN KEY ("CIG")
	  REFERENCES "C##TECNICO_DIPENDENTE"."CONTRATTO" ("CIG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOLLETTA_ACQUA
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ACQUA" ADD CONSTRAINT "FK_BOLLETTA_ACQUA" FOREIGN KEY ("NUMERO_FATTURA")
	  REFERENCES "C##TECNICO_DIPENDENTE"."BOLLETTA" ("NUMERO_FATTURA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOLLETTA_ELETTRICA
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_ELETTRICA" ADD CONSTRAINT "FK_BOLLETTA_ELETTRICA" FOREIGN KEY ("NUMERO_FATTURA")
	  REFERENCES "C##TECNICO_DIPENDENTE"."BOLLETTA" ("NUMERO_FATTURA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOLLETTA_GAS
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."BOLLETTA_GAS" ADD CONSTRAINT "FK_BOLLETTA_GAS" FOREIGN KEY ("NUMERO_FATTURA")
	  REFERENCES "C##TECNICO_DIPENDENTE"."BOLLETTA" ("NUMERO_FATTURA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTRATTO
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" ADD CONSTRAINT "FK_STRUTTURA" FOREIGN KEY ("CENTRO_COSTO")
	  REFERENCES "C##TECNICO_DIPENDENTE"."STRUTTURA" ("CENTRO_COSTO") ENABLE;
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" ADD CONSTRAINT "FK_FORNITORE" FOREIGN KEY ("PARTITA_IVA")
	  REFERENCES "C##TECNICO_DIPENDENTE"."FORNITORE" ("PARTITA_IVA") ENABLE;
  ALTER TABLE "C##TECNICO_DIPENDENTE"."CONTRATTO" ADD CONSTRAINT "FK_POD" FOREIGN KEY ("CODICE_POD")
	  REFERENCES "C##TECNICO_DIPENDENTE"."POD" ("CODICE_POD") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANDATO
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."MANDATO" ADD CONSTRAINT "FK_DIPENDENTE" FOREIGN KEY ("EMAIL_AZIENDALE")
	  REFERENCES "C##TECNICO_DIPENDENTE"."DIPENDENTE" ("EMAIL_AZIENDALE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STRUTTURA
--------------------------------------------------------

  ALTER TABLE "C##TECNICO_DIPENDENTE"."STRUTTURA" ADD CONSTRAINT "FK_DISTRETTO" FOREIGN KEY ("CODICE_DISTRETTO")
	  REFERENCES "C##TECNICO_DIPENDENTE"."DISTRETTO" ("CODICE_DISTRETTO") ENABLE;
