CREATE OR REPLACE FUNCTION CALCOLO_CONSUMO_ANNUO (ANNO CHAR,
DISTRETTO1 CHAR)
RETURN NUMBER IS
CONSUMO_E NUMBER(8,2);
CONSUMO_A NUMBER(8,2);
CONSUMO_G NUMBER(8,2);
CONSUMO_TOT NUMBER (12,2);
ANNO_FUTURO EXCEPTION;
DISTRETTO_INESISTENTE CHAR(6);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
IF ANNO>TO_CHAR(SYSDATE,'YYYY') THEN
RAISE ANNO_FUTURO;
END IF;
SELECT SUM(COSTO) INTO CONSUMO_E
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
JOIN BOLLETTA_ELETTRICA ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_ELETTRICA.NUMERO_FATTURA
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
SELECT SUM(COSTO) INTO CONSUMO_A
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
JOIN BOLLETTA_ACQUA ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_ACQUA.NUMERO_FATTURA
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
SELECT SUM(COSTO) INTO CONSUMO_G
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
JOIN BOLLETTA_GAS ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_GAS.NUMERO_FATTURA
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
CONSUMO_TOT := CONSUMO_G +CONSUMO_A+CONSUMO_E;
RETURN CONSUMO_TOT;
EXCEPTION
WHEN ANNO_FUTURO THEN
RAISE_APPLICATION_ERROR(-20010,'ANNO ERRATO');
RETURN NULL;
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR (-20011,'DISTRETTO INESISTENTE');
RETURN NULL;
END CALCOLO_CONSUMO_ANNUO;