CREATE OR REPLACE FUNCTION CALCOLO_TOT_PAGARE_ANNUO (ANNO CHAR,
DISTRETTO CHAR)
RETURN NUMBER IS
PAGARE_TOT NUMBER(8,2);
ANNO_FUTURO EXCEPTION;
DISTRETTO_INESISTENTE CHAR(6);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO;
IF ANNO>TO_CHAR(SYSDATE,'YYYY') THEN
RAISE ANNO_FUTURO;
END IF;
SELECT SUM(TOT_PAGARE) INTO PAGARE_TOT
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO;
RETURN PAGARE_TOT;
EXCEPTION
WHEN ANNO_FUTURO THEN
RAISE_APPLICATION_ERROR(-20010,'Anno errato');
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20011,'DISTRETTO NON ESISTENTE');
RETURN NULL;
END CALCOLO_TOT_PAGARE_ANNUO;
