CREATE OR REPLACE FUNCTION CALCOLO_IVA_ANNUO (ANNO CHAR, DISTRETTO1
CHAR)
RETURN NUMBER IS
IVA_TOT NUMBER(8,2);
ANNO_FUTURO EXCEPTION;
DISTRETTO_INESISTENTE CHAR(6);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
IF ANNO>TO_CHAR(SYSDATE,'YYYY') THEN
RAISE ANNO_FUTURO;
END IF;
SELECT SUM(IVA) INTO IVA_TOT
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
RETURN IVA_TOT;
EXCEPTION
WHEN ANNO_FUTURO THEN
RAISE_APPLICATION_ERROR(-20010,'Anno errato');
RETURN NULL;
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20011,'DISTRETTO ERRATO');
RETURN NULL;
END CALCOLO_IVA_ANNUO;
