CREATE OR REPLACE PROCEDURE CAMBIO_PERMESSI(EMAIL CHAR, PER CHAR)
IS
ERRORE EXCEPTION;
CON_EMAIL CHAR(50);
BEGIN
SELECT EMAIL_AZIENDALE INTO CON_EMAIL FROM DIPENDENTE WHERE
EMAIL_AZIENDALE = EMAIL;
IF (PER < '0') OR (PER >'3') THEN
RAISE ERRORE;
END IF;
UPDATE DIPENDENTE
SET PRIVILEGIO = PER
WHERE EMAIL_AZIENDALE = EMAIL;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20100,'EMAIL NON ESISTENTE');
WHEN ERRORE THEN
RAISE_APPLICATION_ERROR(-20120,'PERMESSO NON VALIDO');
END;