DROP TABLE DISTRETTO cascade constraints;
DROP TABLE STRUTTURA cascade constraints;
DROP TABLE POD cascade constraints;
DROP TABLE FORNITORE cascade constraints;
DROP TABLE DIPENDENTE cascade constraints;
DROP TABLE CONTRATTO cascade constraints;
DROP TABLE MANDATO cascade constraints;
DROP TABLE BOLLETTA cascade constraints;
DROP TABLE BOLLETTA_GAS cascade constraints;
DROP TABLE BOLLETTA_ELETTRICA cascade constraints;
DROP TABLE BOLLETTA_ACQUA cascade constraints;

CREATE TABLE DISTRETTO(
CODICE_DISTRETTO CHAR(6) PRIMARY KEY,
NOME_DISTRETTO VARCHAR(40) NOT NULL
);
CREATE TABLE STRUTTURA(
CENTRO_COSTO CHAR(10) PRIMARY KEY,
NOME_STRUTTURA VARCHAR(50) NOT NULL,
VIA VARCHAR(50) NOT NULL,
CAP CHAR(5),
SITUAZIONE_GIURIDICA CHAR(20),
CODICE_DISTRETTO CHAR(6) NOT NULL,
CONSTRAINT FK_DISTRETTO FOREIGN KEY (CODICE_DISTRETTO) REFERENCES
DISTRETTO(CODICE_DISTRETTO)
);
CREATE TABLE POD(
CODICE_POD VARCHAR(10) PRIMARY KEY,
LETTURA_MANUALE NUMBER(11,3) DEFAULT NULL,
DATA_LETTURA DATE DEFAULT NULL,
NUMERO_CONTATORE VARCHAR(12)
);
CREATE TABLE FORNITORE (
PARTITA_IVA VARCHAR(13) PRIMARY KEY,
NUMERO_SERVIZIO_CLIENTI VARCHAR(10),
NUMERO_SEDE VARCHAR (11),
INDIRIZZO VARCHAR(50) NOT NULL,
PEC VARCHAR(50),
FAX VARCHAR(18),
NOME VARCHAR(25) NOT NULL
);
CREATE TABLE CONTRATTO (
CIG CHAR(10) PRIMARY KEY,
POTENZA_CONTRATTUALE NUMBER(16,4) NOT NULL,
CONDIZIONE_MERCATO VARCHAR(40) NOT NULL,
DEPOSITO_CAUZIONALE NUMBER(9,2) DEFAULT 0,
TIPO_FORNITURA VARCHAR(30) NOT NULL,
STATO CHAR(1) NOT NULL,
DATA_CESSAZIONE DATE DEFAULT NULL,
PROTOCOLLO_CESSAZIONE VARCHAR(12) DEFAULT NULL,
ADEGUATEZZA CHAR(2) NOT NULL,
PROTOCOLLO_ADEGUATEZZA VARCHAR(12),
DATA_ADEGUATEZZA DATE ,
TIPO CHAR(1),
CENTRO_COSTO CHAR(10) NOT NULL,
PARTITA_IVA VARCHAR(13) NOT NULL,
CODICE_POD VARCHAR(10) NOT NULL,
CONSTRAINT CHECK_STATO CHECK(STATO IN ('0','1')),
CONSTRAINT CHECK_ENERGIA CHECK(TIPO IN ('G','E','A')),
CONSTRAINT CHECK_ADEGUATEZZA CHECK(ADEGUATEZZA IN ('SI','NO')),
CONSTRAINT FK_STRUTTURA FOREIGN KEY(CENTRO_COSTO) REFERENCES
STRUTTURA(CENTRO_COSTO),
CONSTRAINT FK_FORNITORE FOREIGN KEY(PARTITA_IVA) REFERENCES
FORNITORE(PARTITA_IVA),
CONSTRAINT FK_POD FOREIGN KEY(CODICE_POD) REFERENCES
POD(CODICE_POD) ON DELETE SET NULL
);
CREATE TABLE DIPENDENTE (
EMAIL_AZIENDALE VARCHAR(50) PRIMARY KEY,
NOME VARCHAR(20) NOT NULL,
COGNOME VARCHAR(20) NOT NULL,
PRIVILEGIO CHAR(1) NOT NULL,
CHIAVE_ACCESSO CHAR(16) DEFAULT NULL,
CONSTRAINT CHECK_PRIVILEGIO CHECK(PRIVILEGIO IN ('0','1','2'))
);

CREATE TABLE MANDATO (
CODICE_ATTO VARCHAR(8) PRIMARY KEY,
DATA_RECAPITO DATE NOT NULL,
NUMERO_ATTO VARCHAR(9),
TOTALE_PAGAMENTO NUMBER (10,2),
EMAIL_AZIENDALE VARCHAR(40) NOT NULL,
CONSTRAINT FK_DIPENDENTE FOREIGN KEY(EMAIL_AZIENDALE) REFERENCES
DIPENDENTE(EMAIL_AZIENDALE) ON DELETE CASCADE
);
CREATE TABLE BOLLETTA(
NUMERO_FATTURA VARCHAR(15) PRIMARY KEY,
PERIODO VARCHAR(24) NOT NULL,
TOT_PAGARE NUMBER (9,0) NOT NULL,
DATA_EMISSIONE DATE NOT NULL,
IVA NUMBER(7,2) NOT NULL,
IMPOSTE NUMBER (6,2) NOT NULL,
COSTI_GENERALI NUMBER (7,2) NOT NULL,
SCADENZA DATE NOT NULL,
CODICE_ATTO VARCHAR(8) DEFAULT NULL,
CIG CHAR(10) NOT NULL,
CONSTRAINT FK_MANDATO1 FOREIGN KEY(CODICE_ATTO) REFERENCES
MANDATO(CODICE_ATTO),
CONSTRAINT FK_CONTRATTO1 FOREIGN KEY(CIG) REFERENCES CONTRATTO(CIG)
);
CREATE TABLE BOLLETTA_GAS(
TRASPORTO_E_GESTIONE NUMBER (9,2) NOT NULL,
FORNITURA_GAS NUMBER (9,2) NOT NULL,
COSTO NUMBER(9,2) DEFAULT NULL,
CONSUMO_PDR NUMBER(9,2) NOT NULL,
ONERI_DI_SISTEMA NUMBER(9,2) NOT NULL,
NUMERO_FATTURA VARCHAR(15) PRIMARY KEY,
CONSTRAINT FK_BOLLETTA_GAS FOREIGN KEY(NUMERO_FATTURA) REFERENCES
BOLLETTA(NUMERO_FATTURA)
);
CREATE TABLE BOLLETTA_ACQUA(
COSTO NUMBER(9,2) DEFAULT NULL,
ACQUEDOTTO NUMBER (9,2) NOT NULL,
FOGNATURA NUMBER (9,2) NOT NULL,
DEPURAZIONE NUMBER(9,2) NOT NULL,
CONSUMO_ACQUA NUMBER(9,2) NOT NULL,
ONERI_PEREQUAZIONE NUMBER(9,2) NOT NULL,
NUMERO_FATTURA VARCHAR(15) PRIMARY KEY NOT NULL,
CONSTRAINT FK_BOLLETTA_ACQUA FOREIGN KEY(NUMERO_FATTURA)
REFERENCES BOLLETTA(NUMERO_FATTURA)
);
CREATE TABLE BOLLETTA_ELETTRICA(
COSTO NUMBER(9,2) DEFAULT NULL,
ENERGIA_REATTIVA NUMBER (9,2) NOT NULL,
POTENZA_PRELEVATA NUMBER (9,2) NOT NULL,
CTS NUMBER(9,2) DEFAULT 0,
ENERGIA_ATTIVA NUMBER (9,2) NOT NULL,
NUMERO_FATTURA VARCHAR(15) PRIMARY KEY NOT NULL,
SERVIZI_RETE NUMBER(9,2),
SERVIZI_DI_VENDITA NUMBER(9,2),
CONSTRAINT FK_BOLLETTA_ELETTRICA FOREIGN KEY(NUMERO_FATTURA)
REFERENCES BOLLETTA(NUMERO_FATTURA)
);

