CREATE OR REPLACE PROCEDURE CREAZIONE_CHIAVI(EMAIL CHAR)
IS
PASS CHAR(16);
NOME_PR VARCHAR(20);
BEGIN
SELECT NOME INTO NOME_PR FROM DIPENDENTE WHERE EMAIL_AZIENDALE =
EMAIL; SELECT FUNZIONE_DI_HASHING(3,3,6,4) INTO PASS FROM DUAL;
UPDATE DIPENDENTE
SET CHIAVE_ACCESSO = PASS WHERE EMAIL_AZIENDALE = EMAIL;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20100,'ERRORE');
END;