CREATE OR REPLACE FUNCTION CALCOLO_POTENZA_MEDIA_ANNUO (ANNO
CHAR, DISTRETTO1 CHAR)
RETURN NUMBER IS
POT_PREL NUMBER(9,2);
ANNO_FUTURO EXCEPTION;
DISTRETTO_INESISTENTE CHAR(6);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
IF ANNO>TO_CHAR(SYSDATE,'YYYY') THEN
RAISE ANNO_FUTURO;
END IF;
SELECT AVG(POTENZA_PRELEVATA) INTO POT_PREL FROM BOLLETTA_ELETTRICA
JOIN BOLLETTA ON
BOLLETTA.NUMERO_FATTURA=BOLLETTA_ELETTRICA.NUMERO_FATTURA
JOIN CONTRATTO ON CONTRATTO.CIG = BOLLETTA.CIG JOIN STRUTTURA ON
STRUTTURA.CENTRO_COSTO=CONTRATTO.CENTRO_COSTO
JOIN DISTRETTO ON
DISTRETTO.CODICE_DISTRETTO=STRUTTURA.CODICE_DISTRETTO WHERE
EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE) = ANNO AND
DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
RETURN POT_PREL;
EXCEPTION
WHEN ANNO_FUTURO THEN
RAISE_APPLICATION_ERROR(-20010,'Anno errato');
RETURN NULL;
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20011,'DISTRETTO ERRATO');
RETURN NULL;
END CALCOLO_POTENZA_MEDIA_ANNUO;
