CREATE OR REPLACE PROCEDURE SPESE_TOT_BOLLETTE (DATAIN CHAR,
DISTRETTO1 CHAR)
IS
TOTALE NUMBER;
anno_futuro EXCEPTION;
PIPPO CHAR (1);
DISTRETTO_INESISTENTE CHAR(6);
app bolletta.TOT_PAGARE%type;
app1 CONTRATTO.TIPO%type;
CURSOR c1
IS (
SELECT SUM(TOT_PAGARE) as Totale, CONTRATTO.TIPO as Tipo
FROM DISTRETTO JOIN STRUTTURA ON STRUTTURA.CODICE_DISTRETTO =
DISTRETTO.CODICE_DISTRETTO
JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON CONTRATTO.CIG = BOLLETTA.CIG
WHERE EXTRACT(YEAR FROM BOLLETTA.DATA_EMISSIONE)= '2021' AND
DISTRETTO.CODICE_DISTRETTO ='SJK4BZ'
GROUP BY CONTRATTO.TIPO);
BEGIN
SELECT DISTRETTO.CODICE_DISTRETTO INTO DISTRETTO_INESISTENTE FROM
DISTRETTO WHERE DISTRETTO.CODICE_DISTRETTO = DISTRETTO1;
IF DATAIN>TO_CHAR(sysdate,'yyyy')THEN
RAISE anno_futuro;
END IF;
OPEN c1;
FETCH c1 INTO app,app1;
WHILE c1%FOUND LOOP
DBMS_OUTPUT.PUT_LINE('Tipo = ' || app1 ||' Totale =' || app);
FETCH c1 INTO app,app1;
END LOOP;
EXCEPTION
when anno_futuro then
RAISE_APPLICATION_ERROR(-20010,'ANNO INESISTENTE');
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20011,'DISTRETTO INESISTENTE');
END SPESE_TOT_BOLLETTE;
