CREATE OR REPLACE VIEW TABELLONE_STRUTTURA_LUCE AS
SELECT STRUTTURA.CENTRO_COSTO,
BOLLETTA.DATA_EMISSIONE,BOLLETTA.NUMERO_FATTURA,CONTRATTO.CODICE_POD,
BOLLETTA_ELETTRICA.COSTO, BOLLETTA_ELETTRICA.ENERGIA_ATTIVA,
BOLLETTA_ELETTRICA.ENERGIA_REATTIVA,
BOLLETTA_ELETTRICA.POTENZA_PRELEVATA, SERVIZI_DI_VENDITA,
SERVIZI_RETE, BOLLETTA.IMPOSTE, BOLLETTA.IVA
FROM STRUTTURA JOIN CONTRATTO ON CONTRATTO.CENTRO_COSTO =
STRUTTURA.CENTRO_COSTO
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_ELETTRICA ON BOLLETTA_ELETTRICA.NUMERO_FATTURA =
BOLLETTA.NUMERO_FATTURA;
