CREATE OR REPLACE FUNCTION TOT_PAGARE_PRECEDENTE(N_FATT VARCHAR)
RETURN NUMBER IS
SCOOBYDOO VARCHAR(15);
MINNIE NUMBER (9,2);
RONNIE DATE;
D_BOLLETTA DATE;
BEGIN
SELECT (BOLLETTA.NUMERO_FATTURA) INTO SCOOBYDOO FROM BOLLETTA
WHERE BOLLETTA.NUMERO_FATTURA=N_FATT;
SELECT (DATA_EMISSIONE) INTO D_BOLLETTA FROM BOLLETTA WHERE
BOLLETTA.NUMERO_FATTURA=N_FATT;
SELECT TOT_PAGARE INTO MINNIE FROM BOLLETTA WHERE DATA_EMISSIONE =
(SELECT MAX(DATA_EMISSIONE) FROM BOLLETTA WHERE DATA_EMISSIONE
<D_BOLLETTA);
RETURN MINNIE;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20012,'FATTURA ERRATA');
RETURN NULL;
END TOT_PAGARE_PRECEDENTE;