CREATE OR REPLACE PROCEDURE UPDATE_CONTRATTO(CON_CIG CHAR,
DATA_CES DATE, PROT CHAR)
IS
CIG_CONT CHAR(10);
DATA_FUTURA EXCEPTION;
ERRORE EXCEPTION;
ATTIVO CHAR(1);
BEGIN
SELECT CIG INTO CIG_CONT
FROM CONTRATTO WHERE CIG= CON_CIG;
IF DATA_CES > SYSDATE THEN
RAISE DATA_FUTURA;
END IF;
SELECT STATO INTO ATTIVO
FROM CONTRATTO
WHERE CIG = CON_CIG;
IF ATTIVO = '0' THEN
RAISE ERRORE;
END IF;
UPDATE CONTRATTO SET DATA_CESSAZIONE = DATA_CES, STATO= '0',
PROTOCOLLO_CESSAZIONE = PROT
WHERE CIG = CON_CIG;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20015,'CONTRATTO ERRATO');
WHEN DATA_FUTURA THEN
RAISE_APPLICATION_ERROR(-20010,'DATA ERRATA');
WHEN ERRORE THEN
RAISE_APPLICATION_ERROR(-20030,'CONTRATTO GIÀ INATTIVO');
END UPDATE_CONTRATTO;
