CREATE OR REPLACE PROCEDURE UPDATE_LETTURA_POD(DATA_LET DATE, POD1
CHAR, LETTURA NUMBER, BOLLETTA1 CHAR)
IS
CONTROLLO CHAR(1);
CON_NUM NUMBER(10,2);
ECC EXCEPTION;
BEGIN
UPDATE POD
SET DATA_LETTURA = DATA_LET, LETTURA_MANUALE = LETTURA
WHERE CODICE_POD = POD1;
SELECT TIPO INTO CONTROLLO
FROM POD JOIN CONTRATTO ON CONTRATTO.CODICE_POD = POD.CODICE_POD
WHERE POD.CODICE_POD = POD1 AND CONTRATTO.STATO = '1';
IF CONTROLLO = 'A' THEN
SELECT COSTO INTO CON_NUM
FROM POD JOIN CONTRATTO ON CONTRATTO.CODICE_POD = POD.CODICE_POD
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_ACQUA ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_ACQUA.NUMERO_FATTURA
WHERE BOLLETTA.NUMERO_FATTURA = BOLLETTA1;
IF CON_NUM != LETTURA THEN
RAISE ECC;
END IF;
END IF;
IF CONTROLLO = 'G' THEN
SELECT COSTO INTO CON_NUM
FROM POD JOIN CONTRATTO ON CONTRATTO.CODICE_POD =
POD.CODICE_POD
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_GAS ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_GAS.NUMERO_FATTURA
WHERE BOLLETTA.NUMERO_FATTURA = BOLLETTA1;
IF CON_NUM != LETTURA THEN
RAISE ECC;
END IF;
END IF;
IF CONTROLLO = 'E' THEN
SELECT COSTO INTO CON_NUM
FROM POD JOIN CONTRATTO ON CONTRATTO.CODICE_POD =
POD.CODICE_POD
JOIN BOLLETTA ON BOLLETTA.CIG = CONTRATTO.CIG
JOIN BOLLETTA_ELETTRICA ON BOLLETTA.NUMERO_FATTURA =
BOLLETTA_ELETTRICA.NUMERO_FATTURA
WHERE BOLLETTA.NUMERO_FATTURA = BOLLETTA1;
IF CON_NUM != LETTURA THEN
RAISE ECC;
END IF;
END IF;
EXCEPTION
WHEN ECC THEN
DBMS_OUTPUT.PUT_LINE('La lettura inserita non corrisponde con quella della bolletta,
attenzione!');
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20022, 'ERRORE');
END;