CREATE OR REPLACE PROCEDURE UPDATE_ADEGUATEZZA(CON_CIG CHAR,
DATA_ADE DATE, PROT CHAR)
IS
CIG_CONT CHAR(10);
CIG_EXCEPT EXCEPTION;
DATA_FUTURA EXCEPTION;
BEGIN
SELECT CIG INTO CIG_CONT
FROM CONTRATTO WHERE CIG= CON_CIG;
IF DATA_ADE > SYSDATE THEN
RAISE DATA_FUTURA;
END IF;
UPDATE CONTRATTO SET ADEGUATEZZA = 'SI', DATA_ADEGUATEZZA= DATA_ADE,
PROTOCOLLO_ADEGUATEZZA = PROT
WHERE CIG = CON_CIG;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20015,'CONTRATTO INESISTENTE');
WHEN DATA_FUTURA THEN
RAISE_APPLICATION_ERROR(-20010,'DATA_ERRATA');
END UPDATE_ADEGUATEZZA;
